### ISSUE TITLE
highlight a bit more things

### ISSUE THREAD

**Issue by vendethiel** [racklin/livescript-idea#2]
Thanks for this plugin ! It seems a bit "basic" tho : 

![](http://i.imgur.com/vewqVOZ.png)

This might be a choice, but I'd like accesses, function arrows to be highlighted :).

`export` also seems not to be recognized

**Comment by vendethiel** [comment]
``` is not recognized either

**Comment by vendethiel** [comment]
also, ctrl-click or ctrl-w will just select the whole file :(

**Comment by racklin** [comment]
@Nami-Doc Hi, accesses, function arrows can be highlighted, but you must change highlight colors & fonts Settings.
![screenshot on 2013-07-06 at 15 55 50](https://f.cloud.github.com/assets/21985/756448/cb2ed9e6-e611-11e2-8e4e-4d04a0e2511c.png)

And sorry that i have only implemented syntax highlight by flex(lexer).
The ctrl-click ctrl-w must implemented the language parser , i am working hard for it.

Thanks

**Comment by vendethiel** [comment]
Ok, thanks ! Just started using IntelliJ, I don't know much about it !

**Comment by vendethiel** [comment]
Okay, so I just did configure my color scheme. Everything went great except those little points : 
- It seems you can't highlight `@abc`. You hl `@` and `abc` but not only when together?
- `a-b` is not recognized as a single identifier
- A bit too much seems to be recognized as a function

I'd also love to have `export`/`let`/`super` as keywords :)!

**Comment by vendethiel** [comment]
export/let please :) ?

**Comment by racklin** [comment]
@Nami-Doc export is reserved word and it will highlight with error mark.
I will add let keyword now. thanks.

**Comment by vendethiel** [comment]
export is a valid livescript keyword (even if the documentation isn't up to date yet).

try `export a`, `export {a}`, `export a = 5`

**Comment by vendethiel** [comment]
Great ! thanks!
